# Site settings
title: MISE
subtitle: Multidisciplinary Initiative for Space Exploration
description: >
  The Multidisciplinary Initiative for Space Exploration  (MISE) is to elevate the role of Chile in this field. MISE is
  about strengthening both the space research conducted in Chile and developing related engineering sciences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
email: marina.stepanova@usach.cl
logo: img/logos/mise.png
header-image: img/bg-space.jpg

# Build settings
markdown: kramdown

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 115268
  secondary: 4C3B71
  secondary-dark: 021F4B

# Social
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/mise
  - title: envelope
    url: mailto:marina.stepanova@usach.cl
  - title: github
    url: https://github.com/spel-uchile/mise


# Custom settings
# Uses font awesome icons name, without 'fa-' prefix. Examples:
#  space-shuttle user-astronaut globe-americas satellite meteor satellite-dish
# Use '>' after description:, so Jekyll will ignore the line breaks.
research:
  - name: Space physics and space weather
    icon: sun
    description: >
      Our Sun is not only a source of light but also the source of a solar wind. The Earth’s magnetic field shield it
      from such plasma flow, creating the magnetosphere similar to a turbulent wake behind an obstacle. Numerous
      satellites have provided invaluable information about space plasmas, allowing us to understand the e extreme
      processes occurring in the near space, such as geomagnetic storms and substorms, which threaten human operations
      both in space and on ground.

  - name: Astronomy and astrophysics
    icon: satellite-dish
    description: >
      Chile has unique conditions for space exploration and astronomy. We expect to keep contributing to this field in
      three lines: techniques and technologies to keep clean skies for astronomical observations; astronomical
      instruments for use in space; and space and planetary physics for stellar and exoplanetary systems

  - name: Astrobiology and bioengineering
    icon: dna
    description: >
      The hostile conditions of our neighbor planets direct the search of life to the microbial world. The discovery of
      microbial communities in high and low temperature ecosystems such as those present in deep sea hypothermal vents
      or the Dry Valleys and frozen lakes of Antarctica respectively, have extended our definition of  a habitability
      zone where to find extraterrestrial life.

  - name: Engineering science
    icon: satellite
    description: >
      Engineering is key to achieve the scientific goals. We will develop Life in Extreme Environment Labs (LEEL) to
      evaluate technology to sustain life and instruments to gather data to find candidates for aerial and
      space missions. Leveraging from our experience in instrumentation, robotics, solar energy and mining, we will
      focus on its development, transportation, deployment, maintenance and efficiency in space.

partners:
  - name: UCH
    logo: uchile.png
    url: https://uchile.cl

  - name: USACH
    logo: usach.png
    url: https://usach.cl
  - name: PUCV
    logo:
    url: https://www.pucv.cl/

projects:
  - name: SPEL
    area: Nanosatellites
    img: spel.jpg
    url: https://spel.cl

  - name: ISCLab
    area: Software Engineering
    img: isclab.jpg
    url: https://isclab.dcc.uchile.cl

  - name: LAB3
    area: AREA
    img: 3.jpg
    url:

  - name: LAB4
    area: AREA
    img: 4.jpg
    url:

  - name: LAB5
    area: AREA
    img: 5.jpg
    url:

  - name: LAB6
    area: AREA
    img: 6.jpg
    url:

team:
  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:

  - name: Researcher Name
    role: Researcher
    img: profile.jpg
    url:
