# Site settings
title: SPEL
subtitle: Space and Planetary Exploration Laboratory
description: >
  Space and Planetary Exploration Laboratory (SPEL) was built in 2011 in the Electrical Engineering Department of the
  University of Chile to serve as the headquarters of the design, construction, development and operation of the first
  chilean nanosatellite, SUChAI. Since that year, many students have contributed to the SUCHAI project and others,
  extending the areas of the laboratory.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
email: spel@ing.uchile.cl
logo: img/logos/spel.svg
header-image: img/bg-astronaut.jpg

# Build settings
markdown: kramdown

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 636b70
  secondary: d42e12
  secondary-dark: d42e12

# Social
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/spel
  - title: envelope
    url: mailto:spel@ing.uchile.cl
  - title: github
    url: https://github.com/spel-uchile/


# Custom settings
# Uses font awesome icons name, without 'fa-' prefix. Examples:
#  space-shuttle user-astronaut globe-americas satellite meteor satellite-dish
# Use '>' after description:, so Jekyll will ignore the line breaks.
research:
  - name: Space physics and space weather
    icon: space-shuttle
    description: >
      Our Sun is not only a source of light but also the source of a solar wind. The Earth’s magnetic field shields it
      from such plasma flow, creating the magnetosphere similar to a turbulent wake behind an obstacle. Numerous
      satellites have provided invaluable information about space plasmas, allowing us to understand the extreme
      processes occurring in the near space, such as geomagnetic storms and substorms, which threaten human operations
      both in space and on ground.

  - name: Instrumenstation and satellite communications
    icon: satellite-dish
    description: >
      Chile has unique conditions for space exploration and astronomy. We expect to keep contributing to this field in
      three lines: techniques and technologies to keep clean skies for astronomical observations; astronomical
      instruments for use in space; and space and planetary physics for stellar and exoplanetary systems

  - name: Nanosatellites
    icon: satellite
    description: >
      Engineering is key to achieve the scientific goals. We will develop Life in Extreme Environment Labs (LEEL) to
      evaluate technology to sustain life and instruments to gather data to find candidates for aerial and
      space missions. Leveraging from our experience in instrumentation, robotics, solar energy and mining, we will
      focus on its development, transportation, deployment, maintenance and efficiency in space.

partners:
  - name: Universidad de Chile
    short:  UCH
    logo: uchile.png
    url: https://uchile.cl

  - name: Universidad de Santiago de Chile
    short:  USACH
    logo: usach.png
    url: https://usach.cl

  - name: Comisión Chilena de Energía Nuclear
    short: CCHEN
    logo: cchen.png
    url: https://www.cchen.cl/

satellites:
  - name: SUCHAI 1
    about:
    img: suchai1.jpg
    url:

  - name: SUCHAI 2 y 3
    about:
    img: suchai2.jpg
    url:

  - name: PlantSat
    about:
    img: plantsat.jpg
    url:

projects:
  - name: Low Cost Reaction Wheel
    about: >
      For this project a recycled BLDC motor from old HDD was used for which an optimal shape and sized flywheel
      was develop.DRV10987 driver is used for speed control. Actual Engineering Model integrated as 3axis PC104 Std.
      PCB using I2C for communication.
    img: reactionwheel.jpg
    url:

  - name: SUCHAI Flight Software
    about: >
      Open source, modular and extensible nano-satellite flight software. Flight proven in the SUCHAI I CubeSat.
      Portable to FreeRTOS and GNU/Linux.
    img: flightsoftware.jpg
    url: https://github.com/spel-uchile/SUCHAI-Flight-Software

  - name: Flight software architecture
    about: >
      Flight software for satellite is a complex software system. As such, assessing the design and implementation of
      the software is necessary to ensure a safe software behavior.
    img: flightsoftware2.jpg
    url: https://data.spel.cl/

team:
  - name: Marina Stepanova
    degree: Ph.D Physics
    role: Associate professor
    img: mstepanova.jpg
    url: https://fisica.usach.cl/users/marina

  - name: Marcos Diaz
    role: Associate professor
    degree: Ph.D. Electrical Egineering
    img: mdiaz.jpg
    url: http://ingenieria.uchile.cl/facultad/cuerpo-academico/92407/ingenieria-electrica?qui_id=13058

  - name: Alexandre Bergel
    degree: Ph.D. Computer Sciences
    role: Associate professor
    img: abergel.jpg
    url: http://bergel.eu/

  - name: Marcos Orchard
    degree: Ph.D. Electrical and Computer Engineering
    role: Associate professor
    img: morchard.jpg
    url: https://www.cec.uchile.cl/~morchard/

  - name: Carlos Gonzalez
    role: Ph.D. Student
    degree: Ph.D.(c) Electrical Engineering
    img: cgonzalez.jpg
    url: https://www.linkedin.com/in/carlosgonzalezcortes/?locale=en_US

  - name: Marcos Orchard
    degree: Universidad de Chile
    role: Associate professor
    img: morchard.jpg
    url: https://www.cec.uchile.cl/~morchard/

  - name: Gustavo Díaz
    degree: Electrical Engineer
    role: Engineer
    img: gdiaz.jpg
    url:

  - name: Tamara Gutierrez
    degree: Computer Sciences
    role: Undergrad Student
    img: tgutierrez.jpg
    url:

#  - name: Researcher Name
#    degree:
#    role: Researcher
#    img: profile.jpg
#    url: