# Site settings
title: MISE
subtitle: Multidisciplinary Initiative for Space Exploration
description: The Multidisciplinary Initiative for Space Exploration initiative (MISE) is to elevate the role of Chile in space exploration. MISE is about strengthening both the space research conducted in Chile and developing related engineering sciences. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
email: marina.stepanova@usach.cl
logo: img/logos/mise.png
header-image: img/bg-space.jpg

# Build settings
markdown: kramdown

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 115268
  secondary: 4C3B71
  secondary-dark: 021F4B

# Social
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/mise
  - title: envelope
    url: mailto:marina.stepanova@usach.cl
  - title: github
    url: https://github.com/spel-uchile/mise


# Custom settings
research:
  - name: Space physics & weather
    icon: satellite
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

  - name: Evolution & Remote Signals
    icon: dna
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

  - name: Astronomical Signals
    icon: satellite-dish
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

partners:
  - name: UCH
    logo: uchile.png
    url: https://uchile.cl

  - name: USACH
    logo: usach.png
    url: https://usach.cl
  - name: PUCV
    logo:
    url: https://www.pucv.cl/
